//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Desktop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMSEntities : DbContext
    {
        public EMSEntities()
            : base("name=EMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Copay> Copay { get; set; }
        public DbSet<File> File { get; set; }
        public DbSet<Homestead> Homestead { get; set; }
        public DbSet<Meter> Meter { get; set; }
        public DbSet<MeterData> MeterData { get; set; }
        public DbSet<Payment> Payment { get; set; }
        public DbSet<Rate> Rate { get; set; }
        public DbSet<Service> Service { get; set; }
    }
}
