//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Desktop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMSEntities : DbContext
    {
        public EMSEntities()
            : base("name=EMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Copay> Copay { get; set; }
        public DbSet<File> File { get; set; }
        public DbSet<Homestead> Homestead { get; set; }
        public DbSet<Meter> Meter { get; set; }
        public DbSet<MeterData> MeterData { get; set; }
        public DbSet<Payment> Payment { get; set; }
        public DbSet<Rate> Rate { get; set; }
        public DbSet<Service> Service { get; set; }
    }
}
