//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homestead
    {
        public Homestead()
        {
            this.Meter = new HashSet<Meter>();
            this.Payment = new HashSet<Payment>();
        }
    
        public Nullable<int> Number { get; set; }
        public string OwnerName { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<Meter> Meter { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
