//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterData
    {
        public MeterData()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public int IdMeter { get; set; }
        public double Value { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
