//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meter
    {
        public Meter()
        {
            this.MeterData = new HashSet<MeterData>();
        }
    
        public int Id { get; set; }
        public int IdHomestead { get; set; }
        public int MeterNumber { get; set; }
    
        public virtual ICollection<MeterData> MeterData { get; set; }
        public virtual Homestead Homestead { get; set; }
    }
}
