//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meter
    {
        public Meter()
        {
            this.MeterData = new HashSet<MeterData>();
        }
    
        public int Id { get; set; }
        public int IdHomestead { get; set; }
        public int MeterNumber { get; set; }
    
        public virtual ICollection<MeterData> MeterData { get; set; }
    }
}
