//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.MeterData = new HashSet<MeterData>();
        }
    
        public int Id { get; set; }
        public int IdHomestead { get; set; }
        public int IdService { get; set; }
        public Nullable<int> IdFile { get; set; }
        public double Introduced { get; set; }
        public double Entered { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public double Arrear { get; set; }
        public int PackageNumber { get; set; }
    
        public virtual File File { get; set; }
        public virtual Service Service { get; set; }
        public virtual Homestead Homestead { get; set; }
        public virtual ICollection<MeterData> MeterData { get; set; }
    }
}
