//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public Rate()
        {
            this.MeterData = new HashSet<MeterData>();
        }
    
        public int Id { get; set; }
        public int IdService { get; set; }
        public double Value { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ICollection<MeterData> MeterData { get; set; }
    }
}
